apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - "../../crds"
 - "../../apheleia-operator"
 - "../../user-namespace"

images:
  - name: apheleia-operator
    newName: quay.io/QUAY_USERNAME/apheleia-controller
    newTag: dev
  - name: apheleia-analyser
    newName: quay.io/QUAY_USERNAME/apheleia-analyser
    newTag: dev
