apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - "../../crds"
 - "../../apheleia-operator"
 - "../../user-namespace"

images:
  - name: apheleia-operator
    newName: quay.io/QUAY_USERNAME/apheleia-controller
    newTag: dev

patchesJson6902:
- patch: |-
    - op: replace
      path: "/spec/steps/0/image"
      value: "quay.io/QUAY_USERNAME/apheleia-processor:dev"
  target:
    name: apheleia-deploy
    kind: ClusterTask
