apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gradle
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/displayName: Gradle
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  description: >-
    This Task can be used to run a Gradle build.
  workspaces:
    - name: source
      description: The workspace consisting of the gradle project.
    - name: maven-settings
      description: >-
        The workspace consisting of the custom gradle settings
        provided by the user.
  results:
    - name: contaminants
      description: Any community GAVs that have ended up in the final output.
    - name: dependencies
      description: The total number of dependencies in the output
    - name: untrusted-dependencies
      description: The total number of dependencies that came from an untrusted source, such as Maven central
    - name: JAVA_COMMUNITY_DEPENDENCIES
  params:
    - name: IMAGE
      description: Gradle base image.
      type: string
      default: quay.io/redhat-appstudio/hacbs-jdk11-builder:726e0db51aabb540221ae4d45fc7cb12e1fdd1d4
    - name: GOALS
      description: 'The gradle tasks to run (default: build publish)'
      type: array
      default:
        - build
        - publish
    - name: MAVEN_MIRROR_URL
      description: The Maven repository mirror url
      type: string
      default: "http://jvm-build-workspace-artifact-cache.$(context.taskRun.namespace).svc.cluster.local/v1/cache/default/0/"

    - name: CONTEXT_DIR
      description: The directory containing build.gradle
      type: string
      default: "."
    - name: DEPENDENCY_ANALYSER_PATH
      type: string
      description: >-
        The path to use for dependency analysis.
      default: "."
  steps:
    - name: gradle-settings
      image: "registry.access.redhat.com/ubi8/ubi:8.5"
      securityContext:
        runAsUser: 0
      resources:
        requests:
          memory: "128Mi"
          cpu: "10m"
        limits:
          memory: "512Mi"
          cpu: "300m"
      env:
        - name: GRADLE_USER_HOME
          value: $(workspaces.maven-settings.path)/.gradle
      script: |
        #!/usr/bin/env bash

        mkdir -p ${GRADLE_USER_HOME}
        cat > ${GRADLE_USER_HOME}/gradle.properties << EOF
        org.gradle.caching=false
        org.gradle.console=plain
        # This prevents the daemon from running (which is unnecessary in one-off builds) and increases the memory allocation
        org.gradle.daemon=false
        # For Spring/Nebula Release Plugins
        release.useLastTag=true

        # Increase timeouts
        systemProp.org.gradle.internal.http.connectionTimeout=600000
        systemProp.org.gradle.internal.http.socketTimeout=600000
        systemProp.http.socketTimeout=600000
        systemProp.http.connectionTimeout=600000

        # Settings for <https://github.com/vanniktech/gradle-maven-publish-plugin>
        RELEASE_REPOSITORY_URL=file:$(workspaces.source.path)/hacbs-jvm-deployment-repo
        RELEASE_SIGNING_ENABLED=false
        EOF
        cat > ${GRADLE_USER_HOME}/init.gradle << EOF
        allprojects {
            buildscript {
                repositories {
                    maven {
                        name "HACBS Maven Repository"
                        url "$(params.MAVEN_MIRROR_URL)/v1/cache/default/0/"
                        allowInsecureProtocol = true
                    }
                }
            }
            repositories {
                maven {
                    name "HACBS Maven Repository"
                    url "$(params.MAVEN_MIRROR_URL)/v1/cache/default/0/"
                    allowInsecureProtocol = true
                }
            }
        }

        settingsEvaluated { settings ->
            settings.pluginManagement {
                repositories {
                    maven {
                        name "HACBS Maven Repository"
                        url "$(params.MAVEN_MIRROR_URL)/v1/cache/default/0/"
                        allowInsecureProtocol = true
                    }
                }
            }
        }
        EOF

    - name: gradle-tasks
      image: $(params.IMAGE)
      securityContext:
        runAsUser: 0
      env:
        - name: GRADLE_USER_HOME
          value: $(workspaces.maven-settings.path)/.gradle
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      args: [ "$(params.GOALS[*])" ]
      script: |
        #!/usr/bin/env bash

        echo "Default Gradle version is 7.4.2"

        export GRADLE_HOME="/opt/gradle/7.4.2"
        echo "GRADLE_HOME=${GRADLE_HOME}"

        export PATH="${GRADLE_HOME}/bin:${PATH}"
        export LANG="en_US.UTF-8"
        export LC_ALL="en_US.UTF-8"

        gradle -x test  -DAProxDeployUrl=file:$(workspaces.source.path)/hacbs-jvm-deployment-repo $@ || exit 1

    - name: analyse-dependencies
      securityContext:
        runAsUser: 0
      image: quay.io/sdouglas/hacbs-jvm-build-request-processor:dev
      args:
        - analyse-dependencies
        - path
        - $(workspaces.source.path)/$(params.CONTEXT_DIR)/$(params.DEPENDENCY_ANALYSER_PATH)
        - -s
        - $(workspaces.source.path)/$(params.CONTEXT_DIR)/$(params.DEPENDENCY_ANALYSER_PATH)/java-sbom.json
        - -c
        - "$(results.dependencies.path)"
        - -u
        - "$(results.untrusted-dependencies.path)"
        - --task-run-name
        - $(context.taskRun.name)
