---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  steps:
    - name: run
      image: quay.io/sdouglas/apheleia:latest
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: deploy-task
spec:
  taskRef:
    name: deploy
