apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: apheleia-operator
resources:
  - deployment.yaml
  - sa.yaml
  - rbac.yaml

images:
  - name: apheleia-operator
    newName: quay.io/sdouglas/apheleia-controller
    newTag: dev
