apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/jvm-build-service/deploy/crds/base?ref=4224014ae4c3294d62d75757abfebfe8664b4b7d
- https://github.com/redhat-appstudio/jvm-build-service/deploy/operator/base?ref=4224014ae4c3294d62d75757abfebfe8664b4b7d
- https://github.com/redhat-appstudio/jvm-build-service/deploy/operator/config?ref=4224014ae4c3294d62d75757abfebfe8664b4b7d

images:
  - name: hacbs-jvm-operator
    newName: quay.io/redhat-appstudio/hacbs-jvm-controller
    newTag: 4224014ae4c3294d62d75757abfebfe8664b4b7d
