apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/jvm-build-service/deploy/crds/base?ref=b2d6bb458a9dc3d20c01052b9c9752b553c12edb
- https://github.com/redhat-appstudio/jvm-build-service/deploy/operator/base?ref=b2d6bb458a9dc3d20c01052b9c9752b553c12edb
- https://github.com/redhat-appstudio/jvm-build-service/deploy/operator/config?ref=b2d6bb458a9dc3d20c01052b9c9752b553c12edb

images:
  - name: hacbs-jvm-operator
    newName: quay.io/redhat-appstudio/hacbs-jvm-controller
    newTag: b2d6bb458a9dc3d20c01052b9c9752b553c12edb
