/*
Copyright 2021-2022 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	apheleiav1alpha1 "github.com/apheleia-project/apheleia/pkg/apis/apheleia/v1alpha1"
	versioned "github.com/apheleia-project/apheleia/pkg/client/clientset/versioned"
	internalinterfaces "github.com/apheleia-project/apheleia/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/apheleia-project/apheleia/pkg/client/listers/apheleia/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ComponentBuildInformer provides access to a shared informer and lister for
// ComponentBuilds.
type ComponentBuildInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ComponentBuildLister
}

type componentBuildInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewComponentBuildInformer constructs a new informer for ComponentBuild type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewComponentBuildInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredComponentBuildInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredComponentBuildInformer constructs a new informer for ComponentBuild type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredComponentBuildInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApheleiaV1alpha1().ComponentBuilds(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApheleiaV1alpha1().ComponentBuilds(namespace).Watch(context.TODO(), options)
			},
		},
		&apheleiav1alpha1.ComponentBuild{},
		resyncPeriod,
		indexers,
	)
}

func (f *componentBuildInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredComponentBuildInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *componentBuildInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apheleiav1alpha1.ComponentBuild{}, f.defaultInformer)
}

func (f *componentBuildInformer) Lister() v1alpha1.ComponentBuildLister {
	return v1alpha1.NewComponentBuildLister(f.Informer().GetIndexer())
}
