name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        working-directory: java-components
        run: mvn -B package -Dvalidate-format
      - name: Run unit tests
        working-directory: java-components
        run: mvn test
