name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v1
        with:
          repository: 'redhat-appstudio/jvm-build-service'
          path: 'jbs'
          ref: 'main'
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build JBS with Maven
        working-directory: '../jbs/java-components'
        run: mvn -B install -DskipTests
      - name: Build with Maven
        working-directory: java-components
        run: mvn -B package -Dvalidate-format
      - name: Run unit tests
        working-directory: java-components
        run: mvn test
